#!/usr/bin/env python3
"""Curadoria analítica dos 10 casos (notas da rubrica, análise de ligações, acertos/melhorias, próxima ação) e do diagnóstico.
Toda afirmação aponta para evidência (URL do lead + horário; id de nota/chamada). Textos entre aspas marcados como
"sugestão reescrita" são propostas, não falas reais. Sem texto de chat (API v4), critérios dependentes de conteúdo ficam DI,
exceto onde há transcrição local, resumo automático (tratado como resumo, não como transcrição literal) ou nota humana."""
import json, os, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEADS = os.path.join(ROOT, "dados/restrito/leads")
U = lambda lid: f"https://gabrielhabibadv.kommo.com/leads/detail/{lid}"
def R(lid, ts): return f"{U(lid)} · {ts}"
NA, DI = "NA", "DI"

CASES = {}

CASES["79877820"] = dict(
 ratings={
  "c1": {"nota": 4, "justificativa": "Tarefa 'Novo Lead' criada 12:24 e 1ª ligação às 12:32 (11 min após a criação/transferência); retomada no horário combinado (14:53 mensagem, 14:55 ligação de 13 min). Lead silencioso desde 17/09; equipe tentou em 21, 22 e 25/09.", "evidencias": [R(79877820,"17/09 12:32 nota 574832908"), R(79877820,"17/09 14:55 nota 574840506")], "categoria_causa": "habilidade comercial"},
  "c2": {"nota": 3, "justificativa": "Abertura da ligação cita o contato anterior ('você entrou em contato... questão trabalhista') e testa a informação do formulário ('trabalhou sem a carteira assinada?'); a lead corrige (tinha carteira) e a atendente adapta. Não repete o formulário inteiro.", "evidencias": [R(79877820,"17/09 14:55 transcrição local 00:13–00:28")], "categoria_causa": "habilidade comercial"},
  "c3": {"nota": 3, "justificativa": "Situação e problema bem explorados na ligação de 775 s: tempo de casa, data da demissão, função, câmara fria/insalubridade, acidente, jornada, ponto, forma de pagamento. Implicação pouco explorada (não pergunta o impacto financeiro da falta das verbas); avaliação automática também aponta implicação 6/10.", "evidencias": [R(79877820,"17/09 14:55 transcrição 00:28–07:07"), R(79877820,"17/09 15:09 nota 574840516 (resumo automático)")], "categoria_causa": "habilidade comercial"},
  "c4": {"nota": 3, "justificativa": "Identifica verbas rescisórias não pagas, seguro-desemprego, insalubridade, acidente com laudo e possível dano moral; pede foto do laudo e documentos do acidente. Não confirma valores de salário nem checa prescrição (demissão jan/26, dentro do prazo).", "evidencias": [R(79877820,"17/09 14:55 transcrição 10:20–12:32")], "categoria_causa": "habilidade comercial"},
  "c5": {"nota": 4, "justificativa": "Ligação como 1ª ação (não mensagem), retorno no horário que a lead pediu, novas tentativas em 21/09, 22/09 (2 ligações atendidas de 15 s e 10 s com problema de áudio) e 25/09.", "evidencias": [R(79877820,"17/09 12:32"), R(79877820,"21/09 15:42"), R(79877820,"22/09 17:05"), R(79877820,"25/09 10:34")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": 3, "justificativa": "Explica ação trabalhista, honorários de 30% só no êxito, processo online com audiência presencial e possibilidade de acordo. Trechos confusos na transcrição ('tem casos que não marca o dinheiro') — pode ser erro de transcrição; sem promessa de resultado. Condições de honorários ficam para validação do responsável técnico.", "evidencias": [R(79877820,"17/09 14:55 transcrição 07:10–08:48")], "categoria_causa": "habilidade comercial"},
  "c7": {"nota": 3, "justificativa": "Responde à indicação de um amigo (explica como registrar a indicação) e às dúvidas sobre laudo/atestado, pedindo o documento em vez de prometer.", "evidencias": [R(79877820,"17/09 14:55 transcrição 08:53–11:59")], "categoria_causa": "habilidade comercial"},
  "c8": {"nota": 3, "justificativa": "Pergunta de fechamento clara ('podemos dar seguimento? ficou com alguma dúvida?') e próximo passo definido (enviar relação de dados para o contrato; lead envia fotos do laudo). Faltou prazo/hora combinada para o envio e para o retorno.", "evidencias": [R(79877820,"17/09 14:55 transcrição 08:48–12:41"), R(79877820,"17/09 15:10 mensagem")], "categoria_causa": "habilidade comercial"},
  "c9": {"nota": 2, "justificativa": "Após enviar a relação (17/09 15:10) a 1ª cobrança veio em 21/09 15:42 (4 dias, com fim de semana). Depois cadência boa (22 e 25/09). Nenhuma confirmação de recebimento de documentos registrada.", "evidencias": [R(79877820,"17/09 15:10"), R(79877820,"21/09 15:42–15:44")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 2, "justificativa": "Ligações registradas com gravação (bom). Tarefa de 22/09 10:47 nunca concluída (vencida); etapa 'atendimento humano' só em 22/09; nenhuma nota humana resumindo a ligação (há resumo automático). Formulário dizia 'sem carteira' e o caso é 'com carteira' — campo não corrigido.", "evidencias": [R(79877820,"22/09 10:42 tarefa"), R(79877820,"17/09 16:13–16:14 mudanças de etapa")], "categoria_causa": "registro"}},
 calls_analysis=[
  {"call_id": "d8e45993-ea64-4c84-8cef-319c3d056f6c", "transcript_source": "transcrição local (faster-whisper small) — qualidade baixa nos primeiros 30 s", "resumo": "Ligação de 55 s às 12:32: lead não pode falar; combina retorno 'de tarde, umas duas e meia, três horas'; atendente diz que avisará por mensagem antes de ligar. Compromisso cumprido (mensagem 14:53, ligação 14:55).", "trechos": [{"timestamp": "00:38–00:46", "trecho": "Tem algum horário que eu posso [ligar]? — Pode ser de tarde. — Dá para umas duas e meia três horas. — Ótimo, eu te mando mensagem antes de [ligar], tá bom?", "interpretacao": "Boa prática: quando o lead não pode falar, obtém horário e avisa antes de ligar. Reduz ligação perdida.", "alternativa": "(manter) Sugestão reescrita para fixar o compromisso: 'Fechado, Liana: 14h30 eu te ligo deste número. Se mudar algo, me avisa por aqui.'"}], "limites": "trechos iniciais marcados como dúvida pelo modelo"},
  {"call_id": "321880e0-5dc4-4f3e-a275-090d53e46acb", "transcript_source": "transcrição local (faster-whisper small) + resumo automático do CRM (nota 574840514/574840516)", "resumo": "Ligação de 12 min 55 s. Investigação ampla (tempo de casa, demissão em 22/01, verbas não pagas, insalubridade, acidente com corte no dedo, jornada com folgas, ponto, pagamento em conta). Apresenta ação trabalhista, honorários 30% no êxito, processo online. Fecha com 'podemos dar seguimento?' e pede dados para o contrato e foto do laudo. Lead menciona amigo para indicar.", "trechos": [
    {"timestamp": "00:13–00:28", "trecho": "...referente à sua situação trabalhista, que você entrou em contato conosco, você trabalhou sem a carteira assinada? — Não, trabalhei com a carteira assinada.", "interpretacao": "Retoma o contexto do contato e valida a informação do formulário em vez de assumi-la. A lead corrige e a atendente segue sem atrito.", "alternativa": "(manter) Sugestão: registrar a correção no CRM (campo '[TR] situação') logo após a ligação."},
    {"timestamp": "01:00–01:02", "trecho": "Nossa, que absurdo, [nome]. Então, você trabalhou quatro anos lá e no seu último dia...", "interpretacao": "Validação emocional curta e devolução em forma de pergunta: mantém a lead narrando.", "alternativa": "(manter)"},
    {"timestamp": "07:10–07:20", "trecho": "Olha, o que acontece? A senhora precisa [recorrer], porque pelo que eu estou entendendo, eles vão só ganhar tempo com a senhora e não vão te pagar.", "interpretacao": "Transição para a solução. Implicação apenas insinuada ('vão ganhar tempo'); não quantifica o que está em jogo nem pergunta como a falta das verbas afetou a lead (etapa I do SPIN).", "alternativa": "Sugestão reescrita: 'Liana, desde janeiro você está sem essas verbas e sem o seguro-desemprego. Como isso tem pesado no seu mês? [ouvir] Pois é — e cada mês que passa é um mês a menos que a Justiça alcança. Por isso eu quero te mostrar o caminho hoje.'"},
    {"timestamp": "08:48–08:53", "trecho": "Liana, podemos dar seguimento? Ficou com alguma dúvida?", "interpretacao": "Pergunta de fechamento direta, adequada.", "alternativa": "(manter) Variante do roteiro: 'Tem algo que hoje te impede de dar entrada e recuperar o que é seu?'"},
    {"timestamp": "12:33–12:52", "trecho": "Eu vou te mandar aqui a relação [do que precisa] pra gente ir montando o contrato, tá bom? — Tá bom. ... Foi um prazer te conhecer.", "interpretacao": "Encerra com próximo passo, mas sem prazo nem horário de retorno. A lead sumiu depois disso; a 1ª cobrança veio 4 dias depois.", "alternativa": "Sugestão reescrita: 'Vou te mandar a lista agora. Consegue me enviar as fotos hoje até as 18h? Se não der, amanhã às 10h eu te chamo aqui pra ver o que faltou, combinado?'"}],
   "limites": "Transcrição automática local com erros de nomes e trechos marcados como dúvida; tom de voz não avaliado. Honorários e prazos citados ficam para validação do responsável técnico."},
  {"call_id": "ab386399-0ad4-44cb-96ab-4ae08288ddcc", "transcript_source": "transcrição local", "resumo": "15 s em 22/09 17:05: atendente se apresenta e pergunta se a lead lembra da conversa; áudio cai.", "trechos": [], "limites": "curta; provável falha de áudio"},
  {"call_id": "d090bff6-2f81-4477-91f8-d9313fb8450b", "transcript_source": "transcrição local (baixa confiança)", "resumo": "10 s em 22/09 17:05: 'a senhora me ouve?' — falha de áudio; a atendente mandou mensagem em seguida (17:07).", "trechos": [], "limites": "inaudível"}],
 analysis={
  "acertos": ["Ligação como primeiro contato, 11 minutos após a entrada, e retorno exatamente no horário pedido pela lead.", "Investigação ampla e escuta na ligação principal (jornada, ponto, pagamento, acidente, laudo).", "Pergunta de fechamento explícita e pedido de dados para o contrato ainda na ligação.", "Persistência com registro: 5 tentativas de ligação em 8 dias, todas gravadas/registradas."],
  "melhorias": ["Fechar a ligação com prazo e horário: 'fotos até 18h; te chamo amanhã às 10h'. A relação foi enviada às 15:10 e a 1ª cobrança só em 21/09 (4 dias).", "Explorar implicação antes de apresentar a solução (o que a falta das verbas causou; prazo prescricional como urgência real).", "Registrar após a ligação: nota curta com o que foi combinado, correção do campo 'sem carteira' → 'com carteira', tarefa de retorno com data.", "Quando a ligação falha por áudio (22/09), enviar mensagem oferecendo horário alternativo em vez de só registrar a tentativa — houve mensagem, mas sem proposta de horário identificável (texto indisponível)."],
  "evidencias": [R(79877820,"17/09 12:24 tarefa 'Novo Lead' → 12:32 ligação 55 s"), R(79877820,"17/09 14:55 ligação 775 s + resumo automático 15:09"), R(79877820,"21/09 15:42 ligação não atendida; 22/09 17:05 duas ligações curtas; 25/09 10:34 caixa postal"), R(79877820,"22/09 10:47 tarefa vencida não concluída")],
  "conduzir_melhor": ["Sugestão reescrita (pós-ligação, 15:10): 'Liana, foi ótimo falar com você. Segue a lista: nome completo, CPF, endereço, foto da carteira de trabalho e do laudo da coluna. Consegue me mandar hoje até as 18h? Amanhã às 10h eu te chamo aqui pra conferir o que faltou.'", "Sugestão reescrita (D+1, sem resposta): 'Bom dia, Liana! Conseguiu localizar o laudo? Se estiver difícil, me manda só o nome completo e o CPF que eu já começo o contrato e o resto a gente encaixa depois.'", "Sugestão reescrita (após ligação com falha de áudio): 'Liana, a ligação caiu aqui. Posso te ligar de novo às 17h30 ou prefere amanhã de manhã?'"],
  "proxima_acao": "Não executar: enviar mensagem com duas opções de horário para retomar (ex.: hoje 16h ou amanhã 10h) e criar tarefa com data; se sem resposta em 2 dias úteis, registrar motivo provisório ('sem retorno após ligação') e mover para cadência de resgate.",
  "limitacoes": ["Texto das mensagens de WhatsApp não acessível pela API; conteúdo avaliado apenas nas ligações (transcrição local) e no resumo automático.", "Transcrição automática com erros; nomes podem estar incorretos."],
  "confianca": "alta para tempos, ligações e cadência; média para qualidade da condução (transcrição automática); baixa para conteúdo das mensagens.",
  "observado_vs_sugerido": [
    {"ts": "2026-09-17T15:10:00-03:00", "trecho": "[mensagem humana às 15:10 após a ligação — texto indisponível; pela ligação, era a relação de dados para o contrato]", "interpretacao": "Sem prazo combinado, a bola ficou com a lead por 4 dias sem cobrança.", "alternativa": "Sugestão reescrita: mensagem com lista + prazo ('até 18h') + horário do próximo contato ('amanhã 10h te chamo').", "ref": R(79877820,"17/09 15:10")}]})

CASES["80038784"] = dict(
 ratings={
  "c1": {"nota": 2, "justificativa": "Transferência 07:33 (etapa 'atendimento humano'); lead respondeu ao robô 07:37; 1ª ação humana 11:19–11:20 (3,8 h; possivelmente antes do expediente, não confirmado). Mensagem do lead às 15:15 só teve retorno na ligação de 25/09 10:25 (19 h).", "evidencias": [R(80038784,"24/09 07:33 etapa/tag"), R(80038784,"24/09 11:20 mensagens"), R(80038784,"24/09 15:15 → 25/09 10:25")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": 1, "justificativa": "Na ligação a atendente diz que não vê o relatório do assistente ('não aparece esse relatório seu com o nosso assistente') e volta a perguntar função e situação, embora o CRM tenha 'carteira assinada', '>3 anos', 'horas extras não pagas', score 94.", "evidencias": [R(80038784,"25/09 10:25 transcrição 00:29–02:11"), R(80038784,"24/09 07:31 campos [T] e nota de pré-triagem")], "categoria_causa": "integração"},
  "c3": {"nota": 2, "justificativa": "Perguntas fechadas e curtas (função, pretende sair, cartão de ponto, FGTS); sem espaço para narrar; avaliação automática: Situação 5/10, Implicação 4/10.", "evidencias": [R(80038784,"25/09 10:25 transcrição 01:09–01:52"), R(80038784,"25/09 10:29 nota (resumo automático)")], "categoria_causa": "habilidade comercial"},
  "c4": {"nota": 2, "justificativa": "Toca em rescisão indireta, registro de horas e FGTS, mas não conclui enquadramento nem documentos; ligação termina sem qualificação.", "evidencias": [R(80038784,"25/09 10:25 transcrição 01:26–01:52")], "categoria_causa": "habilidade comercial"},
  "c5": {"nota": 3, "justificativa": "Tentativa de ligação 5 min após as primeiras mensagens (11:25, caixa postal) e ligação atendida no dia seguinte às 10:25. Boa iniciativa; faltou nova tentativa após a ligação inconclusiva.", "evidencias": [R(80038784,"24/09 11:25"), R(80038784,"25/09 10:25 ligação 165 s")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": 1, "justificativa": "Explicação mínima de rescisão indireta ('precisa mostrar as falhas da empresa'); não apresenta o que o escritório faz, etapas ou condições.", "evidencias": [R(80038784,"25/09 10:25 transcrição 01:26–01:36")], "categoria_causa": "habilidade comercial"},
  "c7": {"nota": NA, "justificativa": "Lead não levantou objeções; apenas estranhou não haver o relatório.", "evidencias": [], "categoria_causa": None},
  "c8": {"nota": 1, "justificativa": "Ligação encerra com 'o cliente retorna a ligação depois' (resumo automático) sem horário definido; nenhuma ação humana depois de 25/09 10:29.", "evidencias": [R(80038784,"25/09 10:25 transcrição 02:20–02:39"), R(80038784,"25/09 10:29 última mensagem humana")], "categoria_causa": "habilidade comercial"},
  "c9": {"nota": 1, "justificativa": "Sem follow-up entre 25/09 10:29 e o corte (3,5 dias) apesar de a ligação ter ficado inconclusiva.", "evidencias": [R(80038784,"25/09 10:29 → corte 28/09 22:42")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 2, "justificativa": "Tarefa concluída e ligações registradas com gravação; sem nota humana; contexto do robô existe no CRM e não foi usado; sem tarefa de retorno.", "evidencias": [R(80038784,"24/09 11:19 tarefa concluída")], "categoria_causa": "registro"}},
 calls_analysis=[{"call_id": "e1abf0ca-9482-41eb-885b-c616e6fc2aa0", "transcript_source": "transcrição local (faster-whisper small; primeiros 30 s com baixa confiança) + resumo automático (notas de 25/09 10:29)", "resumo": "165 s. Abertura confusa; pergunta função e se pretende sair; explica que rescisão indireta exige provar falhas; pergunta sobre ponto e FGTS; admite não ver o relatório do assistente; sugere que o lead entrou em contato fora do horário; encerra sem próximo passo datado.", "trechos": [
    {"timestamp": "00:27–00:43", "trecho": "O senhor pode me explicar melhor qual era a sua função na sua empresa? ... Me explica qual era a sua função nessa empresa?", "interpretacao": "Reinicia a investigação do zero apesar de o CRM ter carteira assinada, mais de 3 anos e horas extras não pagas (campos [T] e nota de pré-triagem).", "alternativa": "Sugestão reescrita: 'Vi aqui que o senhor está há mais de 3 anos, com carteira assinada, e que as horas extras não estão sendo pagas. Me conta como é o seu horário hoje e como a empresa registra o ponto.'"},
    {"timestamp": "02:01–02:11", "trecho": "Não sei se é o seu celular que está com aquela programação de apagar mensagens ou é o daqui porque não aparece esse relatório seu com o nosso assistente.", "interpretacao": "Expõe uma falha interna ao lead e transfere a dúvida para ele; o resumo do agente existe no CRM (nota de 07:31).", "alternativa": "Sugestão reescrita: 'Eu tenho aqui o resumo do que você conversou com nosso assistente; só quero confirmar dois pontos com você.'"},
    {"timestamp": "02:20–02:39", "trecho": "eu deve ter entrado em contato após nossa horária de atendimento, então... [encerramento] Tudo bem, então é isso.", "interpretacao": "Encerra sem compromisso; o resumo automático registra 'cliente retorna a ligação depois'. Nenhum contato humano posterior.", "alternativa": "Sugestão reescrita: 'Pra eu te orientar direito, preciso de 10 minutos com calma. Hoje às 14h ou amanhã às 9h, qual fica melhor pro senhor? Eu te ligo deste número.'"}],
   "limites": "Transcrição de baixa confiança no início; tom de voz não avaliado (o resumo automático comenta tom, mas não é verificável aqui)."}],
 analysis={
  "acertos": ["Tentativa de ligação 5 minutos após o primeiro contato humano e ligação atendida no dia seguinte.", "Respostas em menos de 1 h durante a tarde de 24/09."],
  "melhorias": ["Abrir a ligação com o que o robô e o formulário já colheram (score 94, carteira assinada, horas extras); não pedir ao lead para repetir.", "Nunca encerrar ligação inconclusiva sem horário: oferecer duas opções e criar tarefa.", "Retomar em até 1 dia útil após ligação inconclusiva; aqui não houve nenhuma ação em 3,5 dias.", "Ler o resumo e os campos do lead no CRM antes de ligar (a nota do assistente estava no lead)."],
  "evidencias": [R(80038784,"24/09 07:31 nota de pré-triagem e campos [T]"), R(80038784,"25/09 10:25 ligação 165 s (transcrição local)"), R(80038784,"25/09 10:29 última ação humana")],
  "conduzir_melhor": ["Sugestão reescrita (abertura): 'Bom dia! Aqui é a Dra. Cybele, do escritório Gabriel Habib. Vi que você falou com nosso assistente sobre horas extras não pagas, com carteira assinada há mais de 3 anos. Está podendo falar 10 minutos agora?'", "Sugestão reescrita (fechamento): 'Vou te mandar por aqui o que preciso ver: prints do ponto ou escala e os 3 últimos holerites. Amanhã às 9h eu te ligo pra gente decidir o caminho.'"],
  "proxima_acao": "Não executar: mensagem propondo dois horários de ligação e pedindo escala/holerites; tarefa com data; registrar nota da ligação de 25/09.",
  "limitacoes": ["Texto das mensagens indisponível; parte da condução pode ter ocorrido por texto entre 11:20 e 15:11 de 24/09.", "Início da transcrição com baixa confiança."],
  "confianca": "alta para tempos e ligações; média para qualidade da ligação.",
  "observado_vs_sugerido": [{"ts": "2026-09-25T10:25:00-03:00", "trecho": "não aparece esse relatório seu com o nosso assistente", "interpretacao": "Falha de retomada de contexto exposta ao lead; o resumo existia no CRM.", "alternativa": "Sugestão reescrita: 'Tenho aqui o resumo do que você conversou com nosso assistente; vou confirmar só dois pontos.'", "ref": R(80038784,"25/09 10:25 transcrição 02:01–02:11")}]})

CASES["77456896"] = dict(
 ratings={
  "c1": {"nota": 2, "justificativa": "Junho: tarefa concluída em 34 min e 3 mudanças de etapa em 2 h sem contato registrado; notas de 09/06 e 23/06 dizem 'liguei, não atende'. Julho: 4 tentativas não atendidas. Depois 57 dias sem ação (22/07 → 17/09). Setembro: cadência boa (17, 25 e 28/09).", "evidencias": [R(77456896,"08/06 10:48–12:07"), R(77456896,"09/06 13:31 nota 'já liguei'"), R(77456896,"22/07 12:02 → 17/09 12:03")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto de mensagens; ligação de 25/09 só via resumo automático.", "evidencias": [], "categoria_causa": None},
  "c3": {"nota": 4, "justificativa": "Transcrição de 25/09: perguntas de situação (onde mora, desde quando, idade, embarcado, adicionais, PPPs) levam à descoberta de uma segunda oportunidade (aposentadoria especial). Situação e problema bem cobertos; implicação tratada de forma breve ('não vamos perder tempo').", "evidencias": [R(77456896,"25/09 11:39 transcrição 05:32–09:38")], "categoria_causa": "habilidade comercial"},
  "c4": {"nota": 3, "justificativa": "Pede CPF, endereço e fotos dos PPPs; distingue auxílio-acidente de aposentadoria especial. Serviço previdenciário tratado com os requisitos próprios, não com o roteiro de vínculo.", "evidencias": [R(77456896,"25/09 11:52 nota (resumo automático)")], "categoria_causa": "habilidade comercial"},
  "c5": {"nota": 4, "justificativa": "10 tentativas de saída registradas (3 atendidas), incluindo retentativas no mesmo dia e após mensagens sem resposta. Lead nunca escreveu no WhatsApp registrado; a ligação foi o canal que funcionou.", "evidencias": [R(77456896,"07/07, 16/07, 22/07, 17/09, 25/09, 28/09 notas de chamada")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": 3, "justificativa": "Transcrição: honorários (30% dos atrasados + 30% dos 12 primeiros meses), prazo 3–4 meses e pagamento só se o INSS pagar explicados; o lead pede para falar mais devagar (04:31). Condições para validação do responsável técnico.", "evidencias": [R(77456896,"25/09 11:39 transcrição 01:29–02:05 e 04:31")], "categoria_causa": "habilidade comercial"},
  "c7": {"nota": 3, "justificativa": "Dúvidas sobre documentação e custo respondidas (segundo o resumo automático).", "evidencias": [R(77456896,"25/09 11:52 nota")], "categoria_causa": "habilidade comercial"},
  "c8": {"nota": 3, "justificativa": "Compromissos claros: lead envia dados e PPPs 'até amanhã'; escritório monta contrato e envia vídeo 'segunda-feira'. Sem tarefa criada para esses prazos.", "evidencias": [R(77456896,"25/09 11:52 nota")], "categoria_causa": "registro"},
  "c9": {"nota": 3, "justificativa": "Cobranças em 25/09 13:45–17:00 e 28/09 (mensagens + ligações). Não há evidência de envio do vídeo/contrato prometido para segunda (28/09) — texto indisponível.", "evidencias": [R(77456896,"25/09 13:45–17:00"), R(77456896,"28/09 14:19–17:21")], "categoria_causa": "habilidade comercial"},
  "c10": {"nota": 2, "justificativa": "Notas humanas curtas em junho (bom); ligações de junho não registradas (integração posterior?); etapa Negociação desde 08/06 sem contato comprovado; nenhuma tarefa para os prazos combinados em 25/09; 6 ligações sem link de gravação.", "evidencias": [R(77456896,"08/06 12:07 etapa Negociação"), R(77456896,"25/09 sem tarefa")], "categoria_causa": "registro"}},
 calls_analysis=[{"call_id": "ligação 25/09 11:39 (629 s) — transcrição local disponível", "transcript_source": "transcrição local (faster-whisper small) + resumo automático do CRM (nota 25/09 11:52)", "resumo": "10 min 29 s. Abertura direta ('só faltam os seus dados para montar o contrato'); o lead está embarcado e sem documentos à mão; a atendente aceita nome, CPF e endereço por mensagem. Explica honorários (30% dos atrasados + 30% dos 12 primeiros meses) e prazo de 3–4 meses; o lead pede que fale mais devagar. Coleta nome e endereço, investiga zona rural, idade (62), 25 anos embarcado, insalubridade/periculosidade e 56 PPPs, e identifica possível aposentadoria especial (decisão recente do STF). Fecha: PPPs por foto amanhã; contrato do auxílio-acidente e vídeo na segunda.", "trechos": [
    {"timestamp": "00:19–01:08", "trecho": "a gente está tentando dar seguimento, só falta os seus dados pra gente montar o contrato ... pode ser até digitado aqui: nome completo, CPF e endereço.", "interpretacao": "Remove atrito: aceita os dados por mensagem quando o lead não tem documentos à mão. Boa prática de fechamento.", "alternativa": "(manter)"},
    {"timestamp": "01:29–02:05 e 04:31", "trecho": "Aqui no escritório a gente cobra 30% do valor que o senhor receber dos atrasados ... mais 30% sobre os 12 primeiros meses. — [lead] Fala devagar, porque você falou muito rápido.", "interpretacao": "Condições apresentadas com clareza de conteúdo, mas rápido demais para o lead (ele pede para desacelerar). Condições comerciais ficam para validação do responsável técnico.", "alternativa": "Sugestão reescrita: 'Vou explicar em duas partes e depois te mando por escrito. Primeiro: só pagamos se o INSS pagar. Segundo: quanto. Pode me interromper.'"},
    {"timestamp": "05:32–09:38", "trecho": "existe a questão da aposentadoria rural... — Sempre trabalho embarcado. — ...o senhor recebe algum adicional de insalubridade? — ...tenho 56 PPP. — Ótimo... o senhor pode ter a possibilidade de se aposentar como especial.", "interpretacao": "Investigação ativa que descobre uma segunda oportunidade (aposentadoria especial) a partir de perguntas de situação. Exemplo de SPIN bem aplicado a serviço previdenciário.", "alternativa": "(manter) Registrar a nova oportunidade como nota e etapa própria no CRM."},
    {"timestamp": "09:38–10:19", "trecho": "Então não vamos perder tempo. Assim que o senhor puder amanhã, o senhor me encaminha por foto. Aí na segunda-feira eu te mando um vídeo ... vou montar o nosso contrato referente ao auxílio-acidente [ainda hoje].", "interpretacao": "Próximos passos datados dos dois lados (bom); nenhuma tarefa criada no CRM e não há evidência de envio do contrato/vídeo (texto indisponível).", "alternativa": "Sugestão: tarefa 'enviar contrato + vídeo' para 28/09 09:00 e mensagem de confirmação logo após a ligação."}],
   "limites": "Trecho 08:19–09:02 é artefato da transcrição (repetição de 'Entendo'); nomes com erros; tom não avaliado. Notas de junho indicam ligações não registradas no CRM."}],
 analysis={
  "acertos": ["Persistência pertinente por ligação em lead que não responde por texto (10 tentativas, 3 atendidas).", "Ligação longa com investigação adequada ao serviço previdenciário e compromissos bilaterais datados.", "Notas humanas registrando tentativas em junho."],
  "melhorias": ["Evitar o 'buraco' de 57 dias: lead em Negociação sem nenhuma ação entre 22/07 e 17/09 — definir regra de cadência ou mover para resgate com motivo.", "Não avançar etapas (Em atendimento → Análise → Negociação em 2 h) sem contato comprovado; etapa deve refletir a realidade.", "Criar tarefa para cada compromisso combinado na ligação (docs 'amanhã', vídeo 'segunda').", "Confirmar por mensagem, logo após a ligação, o que foi combinado e o que o escritório vai enviar."],
  "evidencias": [R(77456896,"08/06 10:48–12:07 tarefa e 3 etapas"), R(77456896,"22/07 → 17/09 sem ação"), R(77456896,"25/09 11:39 ligação 629 s + resumo 11:52"), R(77456896,"28/09 14:22–14:28 três tentativas")],
  "conduzir_melhor": ["Sugestão reescrita (pós-ligação 25/09): 'Seu Rômulo, obrigado pela conversa. Combinamos: o senhor me manda até amanhã CPF, endereço e as fotos dos PPPs; na segunda eu te envio o contrato e um vídeo explicando. Qualquer dúvida, me chama aqui.'", "Sugestão reescrita (segunda, 28/09): 'Bom dia! Como prometido, segue o vídeo e o contrato. Consegue assinar hoje? Se preferir, revisamos juntos por ligação às 15h.'"],
  "proxima_acao": "Não executar: enviar (ou confirmar o envio de) contrato e vídeo prometidos; criar tarefa de assinatura com prazo; registrar nota com status dos documentos.",
  "limitacoes": ["Ligações de junho não constam no CRM (apenas notas); tempos até o 1º contato não são confiáveis para este caso (indicador 'h_transf_primeira_tentativa' = 700 h reflete registro, não comportamento).", "Sem texto de mensagens."],
  "confianca": "média",
  "observado_vs_sugerido": []})

CASES["79763954"] = dict(
 ratings={
  "c1": {"nota": 3, "justificativa": "Contato humano 1 min após a criação; respostas em minutos ao longo de 15/09; contratação no mesmo dia. Após a ativação, 2 mensagens do lead (15/09 17:24) e mais 3 até 17/09 sem retorno humano por 13 dias (pós-venda).", "evidencias": [R(79763954,"15/09 12:04–12:39"), R(79763954,"15/09 17:24 → 28/09 16:58")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto; ligação só via resumo automático (transcrição local pendente no corte).", "evidencias": [], "categoria_causa": None},
  "c3": {"nota": 3, "justificativa": "Resumo automático da ligação de 28 min: período trabalhado, função, filiais, câmaras frias, horas extras em fins de semana, riscos — investigação rica; o próprio resumo sugere evitar repetição de perguntas.", "evidencias": [R(79763954,"15/09 16:14 nota (resumo automático)")], "categoria_causa": "habilidade comercial"},
  "c4": {"nota": 3, "justificativa": "Foco em insalubridade e horas extras; pede documentos de suporte. Lead saiu em ago/2023 — prescrição de 2 anos vencida em ago/2025 salvo particularidades: ponto a validar pelo responsável técnico (não avaliado aqui).", "evidencias": [R(79763954,"15/09 16:14 nota (resumo automático)")], "categoria_causa": "habilidade comercial"},
  "c5": {"nota": 4, "justificativa": "Ligação de 28 min 3,7 h após a criação, no meio da conversa por texto, seguida de avanço para Assinatura em 5 min.", "evidencias": [R(79763954,"15/09 15:45 ligação 1714 s (registrada na conta de integração)")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": 3, "justificativa": "Processo explicado com prazo (elaboração em 10 dias úteis) segundo o resumo automático.", "evidencias": [R(79763954,"15/09 16:14 nota")], "categoria_causa": "habilidade comercial"},
  "c7": {"nota": 3, "justificativa": "Dúvidas sobre documentação tratadas (resumo automático).", "evidencias": [R(79763954,"15/09 16:14 nota")], "categoria_causa": "habilidade comercial"},
  "c8": {"nota": 4, "justificativa": "Assinatura e ativação no mesmo dia (etapas 16:19 e 17:37; nota 'Cliente ativado').", "evidencias": [R(79763954,"15/09 16:19 → 17:37")], "categoria_causa": "habilidade comercial"},
  "c9": {"nota": 2, "justificativa": "Contratação concluída, mas 5 mensagens do lead pós-ativação (15–17/09) ficaram 13 dias sem retorno humano.", "evidencias": [R(79763954,"15/09 18:29–17/09 08:53"), R(79763954,"28/09 16:58")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 2, "justificativa": "Ligação registrada no usuário 'Marketing Evolve' (ramal não mapeado); serviço e origem não preenchidos; sem notas humanas; sem tarefas.", "evidencias": [R(79763954,"15/09 15:45 nota de chamada created_by 10348307")], "categoria_causa": "integração"}},
 calls_analysis=[{"call_id": "f6e3df23-afd6-4486-b771-0e00e045dcae (15/09 15:45, 1714 s) — registrada na conta de integração", "transcript_source": "transcrição local (faster-whisper small; qualidade baixa nos primeiros minutos) + resumo automático do CRM (nota 15/09 16:14)", "resumo": "28 min. Abertura conecta ao caso de um colega já atendido pelo escritório (indicação). Investigação longa: entrada em 2016, conferente de inventário desde 2018, câmaras frias/congelados, sem adicional de insalubridade, provas (fotos, testemunhas), filiais, jornada, alteração de cargo com documento assinado. Aos 23:53 explica o processo ('entrevista → base do processo'), lista as teses (insalubridade, dano moral por trabalho em altura) e é transparente sobre prescrição das horas extras. Encerra falando de valor estimado a buscar.", "trechos": [
    {"timestamp": "00:18–00:46", "trecho": "prazer, o nome é Juliana ... nós já fazemos o processo do seu colega ... tá fluindo tudo muito bem ... em breve ele já tá recebendo", "interpretacao": "Retomada de contexto por indicação: usa o caso do colega para gerar confiança. Cuidado: 'em breve já está recebendo' é promessa sobre caso de terceiro — evitar.", "alternativa": "Sugestão reescrita: 'Seu colega Joab está com o caso conosco e o processo segue bem. Cada caso tem seu tempo, mas vamos usar a mesma base para o seu.'"},
    {"timestamp": "02:54–03:26", "trecho": "O que você tem de prova a respeito dessa questão do frio? Você tem foto dentro de alguma geladeira? ... um dia da sua audiência para ser sua testemunha", "interpretacao": "Trata a objeção 'não tenho prova' proativamente (roteiro 05B parte 3) e amplia para testemunhas.", "alternativa": "(manter)"},
    {"timestamp": "06:04–06:40", "trecho": "Esse balanço, era finais de semana? — Sábado e domingo. Só que a gente não batia ponto... eles pagavam na mão. — Por fora, né?", "interpretacao": "Pergunta de problema bem feita: revela trabalho em fins de semana sem registro e pago por fora — fato central para o pedido.", "alternativa": "(manter)"},
    {"timestamp": "10:25–12:23", "trecho": "Eu vou tentar reformular a minha pergunta. É só para saber o que a gente vai pedir no seu processo... Se você chegar lá no processo e falar que você tirava a folga, o juiz vai entender que você tirava a folga certa.", "interpretacao": "Reformula quando o lead não entende (boa escuta). O trecho sobre o que dizer no processo toca em orientação de depoimento: ponto para o responsável técnico validar a forma de explicar (não é avaliação jurídica desta auditoria).", "alternativa": "Sugestão: 'Preciso entender exatamente como era, porque o cálculo do processo parte do que de fato acontecia.'"},
    {"timestamp": "23:53–24:17", "trecho": "Vou explicar como é que funciona mais ou menos, tá? Esse primeiro passo que a gente está dando é a nossa entrevista. A gente colhe informações com você ... e aí a gente cria a base do seu processo", "interpretacao": "Explicação clara do processo, mas só aos 24 min; o lead ficou 20 min sem saber para onde a conversa ia.", "alternativa": "Sugestão: apresentar o mapa da conversa na abertura ('vou te fazer perguntas por uns 10 minutos, depois te explico o que dá para pedir e como funciona')."},
    {"timestamp": "25:00–25:17", "trecho": "Você comentou sobre o seu horário, sobre as horas extras. Eu vou confirmar direitinho, mas eu acredito que já estejam prescritas, tá? A gente pode entrar com processo trabalhista até dois anos depois do último dia trabalhado.", "interpretacao": "Transparência sobre prescrição e compromisso de confirmar — boa prática. (Saída em ago/2023: o prazo de 2 anos é ponto técnico a validar pelo responsável.)", "alternativa": "(manter) Registrar a dúvida técnica em nota para o jurídico."}],
   "limites": "Transcrição automática com muitos trechos de baixa confiança; nomes incertos; tom não avaliado. Ligação atribuída ao usuário 'Marketing Evolve' — pelo contexto, atendente Juliana."}],
 analysis={
  "acertos": ["Jornada completa em 5 h 33 min: contato humano imediato, ligação longa no momento certo, assinatura e ativação no mesmo dia.", "Dupla de atendentes alternando sem deixar o lead esperar durante a negociação."],
  "melhorias": ["Pós-venda: responder às mensagens do cliente ativado (5 mensagens em 3 dias sem retorno) ou definir quem responde após a ativação.", "Preencher serviço/origem e registrar nota da ligação (o resumo automático existe, mas não substitui a decisão humana)."],
  "evidencias": [R(79763954,"15/09 12:04 criação; 12:05 1ª mensagem humana"), R(79763954,"15/09 15:45 ligação 1714 s"), R(79763954,"15/09 17:37 Ativação"), R(79763954,"15/09 17:24–17/09 08:53 mensagens do lead sem retorno")],
  "conduzir_melhor": ["Sugestão reescrita (pós-ativação): 'Wellington, bem-vindo! A partir de agora quem cuida do seu caso é [nome]. Recebi suas mensagens de ontem; nos próximos dias te enviamos a lista de documentos. Qualquer dúvida, é aqui mesmo.'"],
  "proxima_acao": "Não executar: definir responsável pelo pós-ativação e responder às mensagens pendentes do cliente.",
  "limitacoes": ["Sem texto; ligação avaliada por resumo automático.", "Aderência da contratação a prazos prescricionais é ponto técnico, fora desta auditoria."],
  "confianca": "alta para linha do tempo; média para condução.",
  "observado_vs_sugerido": []})

CASES["79490552"] = dict(
 ratings={
  "c1": {"nota": 3, "justificativa": "Contato humano 1 min após a criação (lead outbound/evento); respostas no mesmo turno na maior parte; episódios de 6,5 h (15/09 manhã) e 6,3 h (17/09). Após a ativação: 167 h (17→24/09) e pendência aberta de 101 h no corte.", "evidencias": [R(79490552,"02/09 10:37"), R(79490552,"17/09 15:12 → 24/09 14:15"), R(79490552,"24/09 17:35 sem retorno humano")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c3": {"nota": DI, "justificativa": "Sem texto nem ligação.", "evidencias": [], "categoria_causa": None},
  "c4": {"nota": DI, "justificativa": "Passou por Validação de documentação e Ativação (decisão humana), mas o conteúdo da qualificação não é acessível.", "evidencias": [R(79490552,"15/09 16:19 → 17:31")], "categoria_causa": None},
  "c5": {"nota": NA, "justificativa": "Nenhuma ligação registrada; contratação concluída por texto em 13 dias. Não penalizado (roteiro admite fechamento por texto); não há evidência de oferta ou recusa de ligação.", "evidencias": [], "categoria_causa": None},
  "c6": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c7": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c8": {"nota": 4, "justificativa": "Etapas Análise (02/09), atendimento humano (02/09), Validação de documentação e Ativação (15/09) com tarefas de acompanhamento.", "evidencias": [R(79490552,"15/09 16:19 e 17:31")], "categoria_causa": "habilidade comercial"},
  "c9": {"nota": 2, "justificativa": "Tarefas criadas e concluídas até a ativação (bom). Pós-ativação: 12 mensagens do cliente em 24/09 respondidas com 2 h de atraso e a última (17:35) sem retorno humano até o corte; robô respondeu.", "evidencias": [R(79490552,"24/09 14:23–14:52"), R(79490552,"24/09 17:35 → robô 18:01")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 2, "justificativa": "Tarefas com resultado e etapas coerentes; serviço e origem sem preenchimento ('Outbound Evento' só na sub-origem); sem notas.", "evidencias": [R(79490552,"02/09 13:39 tarefa; 15/09 15:07 tarefa")], "categoria_causa": "registro"}},
 calls_analysis=[],
 analysis={
  "acertos": ["Lead de evento trabalhado no mesmo minuto da criação e contratado em 13 dias por texto, com tarefas de acompanhamento cumpridas.", "Retomadas em 11/09 e 15/09 sem depender do lead."],
  "melhorias": ["Pós-ativação: quem responde? Última mensagem do cliente (24/09 17:35) sem retorno humano no corte."],
  "evidencias": [R(79490552,"02/09 10:37–10:43 humano e robô"), R(79490552,"15/09 17:31 Ativação"), R(79490552,"24/09 17:35 → 18:01 robô")],
  "conduzir_melhor": ["Sugestão reescrita (pós-ativação, ao receber documentos): 'Recebi suas 12 mensagens, obrigado! Vou conferir e te retorno até as 16h com o que ainda falta.'"],
  "proxima_acao": "Não executar: responder à mensagem pendente de 24/09 e confirmar recebimento/conferência de documentos.",
  "limitacoes": ["Sem texto; qualidade da condução não avaliável; sem ligações."],
  "confianca": "alta para tempos; baixa para condução.",
  "observado_vs_sugerido": []})

CASES["79533290"] = dict(
 ratings={
  "c1": {"nota": 2, "justificativa": "Início excelente (1ª mensagem humana 6 min após a criação; troca intensa 11:22–12:38). Lacuna: lead silencioso desde 04/09 12:38 e nenhuma ação humana entre 04/09 15:19 e 17/09 10:36 (13 dias). Em 26/09 (sábado) lead enviou 5 mensagens; retorno na segunda 28/09 10:49 (49 h).", "evidencias": [R(79533290,"04/09 11:12"), R(79533290,"04/09 15:19 → 17/09 10:36"), R(79533290,"26/09 09:44 → 28/09 10:49")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c3": {"nota": DI, "justificativa": "Sem texto; reunião de 24/09 sem registro de conteúdo.", "evidencias": [], "categoria_causa": None},
  "c4": {"nota": DI, "justificativa": "Sem texto. Campos do robô: carteira assinada, irregularidade 'discriminatória', score 80.", "evidencias": [], "categoria_causa": None},
  "c5": {"nota": 2, "justificativa": "Única tentativa de ligação em 28/09 (caixa postal), 24 dias após a entrada. A reunião de 24/09 (tarefa 'Reunião realizada') ocorreu, canal não registrado. Sem tentativa de ligação nos 13 dias de silêncio.", "evidencias": [R(79533290,"28/09 14:41"), R(79533290,"24/09 18:45 tarefa 'Reunião realizada'")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c7": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c8": {"nota": 3, "justificativa": "Negociação em 04/09; reunião realizada em 24/09 com próximo passo registrado (enviar documentos para contratação; pegar documentos e provas).", "evidencias": [R(79533290,"04/09 16:10 etapa"), R(79533290,"24/09 18:45 tarefa")], "categoria_causa": "habilidade comercial"},
  "c9": {"nota": 2, "justificativa": "Após a reunião, cobrança em 25/09 (tarefa concluída 'esperando documentação'); lead respondeu no sábado e o retorno veio na segunda; 28/09 4 mensagens + ligação. Mas 13 dias parados entre 04 e 17/09 em Negociação.", "evidencias": [R(79533290,"25/09 14:00"), R(79533290,"28/09 12:29–14:41")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 3, "justificativa": "Tarefas com resultado ('atendimento whatsapp', 'Em andamento', 'esperando a documentação'); etapas coerentes; sem nota da reunião; serviço não preenchido.", "evidencias": [R(79533290,"24/09 18:45 tarefa")], "categoria_causa": "registro"}},
 calls_analysis=[],
 analysis={
  "acertos": ["Resposta em 6 minutos à entrada e condução intensa no 1º dia; Negociação no mesmo dia.", "Reunião realizada e próximo passo registrado em tarefa com prazo (24/09)."],
  "melhorias": ["Regra de cadência para Negociação: 13 dias sem ação humana após o lead parar de responder (04→17/09). O Playbook prevê retomadas em 1 h, 6 h, 24 h, 48 h, 4 d, 7 d — nenhuma ocorreu.", "Oferecer ligação no 1º dia (troca de 100+ mensagens por texto) e ao retomar em 17/09.", "Registrar nota da reunião de 24/09 (o que foi apresentado, objeções, documentos pedidos)."],
  "evidencias": [R(79533290,"04/09 11:06–12:38"), R(79533290,"04/09 15:19 → 17/09 10:36 (13 dias)"), R(79533290,"24/09 18:45 tarefa 'Reunião realizada'")],
  "conduzir_melhor": ["Sugestão reescrita (05/09, D+1 sem resposta): 'Oi [nome], ontem conversamos bastante sobre a sua saída. Pra eu te dar um caminho concreto, posso te ligar hoje às 15h? São 10 minutos.'", "Sugestão reescrita (26/09, sábado, resposta rápida): 'Recebi! Segunda de manhã eu confiro tudo e te retorno até as 11h.'"],
  "proxima_acao": "Não executar: conferir os documentos enviados em 26/09, responder ponto a ponto e agendar ligação para assinatura; tarefa com data.",
  "limitacoes": ["Sem texto; canal da reunião de 24/09 não registrado (não há ligação nesse dia no CRM)."],
  "confianca": "alta para tempos; baixa para conteúdo.",
  "observado_vs_sugerido": []})

CASES["79358770"] = dict(
 ratings={
  "c1": {"nota": 1, "justificativa": "Boa resposta inicial (27/08 10:28, 7,8 h após criação às 02:41; troca ativa 11:22–11:36). Depois: lead pediu documentos? (tarefa 04/09 'ver se encaminhou documentos' para 08/09) e a última mensagem do lead (04/09 14:26) só teve ação humana em 25/09 (21 dias); tarefa concluída 17 dias após o prazo.", "evidencias": [R(79358770,"27/08 10:28"), R(79358770,"04/09 14:26 → 25/09 14:15"), R(79358770,"04/09 14:26 tarefa vencida 08/09 → concluída 25/09")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto. Observação: robô e humano responderam ao lead nos mesmos minutos (27/08 11:19–11:24; 03/09; 04/09).", "evidencias": [R(79358770,"27/08 11:19–11:24")], "categoria_causa": "integração"},
  "c3": {"nota": DI, "justificativa": "Sem texto de mensagens; ligação de 4 s.", "evidencias": [], "categoria_causa": None},
  "c4": {"nota": 3, "justificativa": "Nota humana de 04/09 registra fatos relevantes: acidente 22/01/2026, afastamento, cirurgia, benefício cortado, ação com outro advogado, desejo de auxílio-acidente + rescisão indireta. Caso mistura previdenciário e trabalhista; qualificação captada.", "evidencias": [R(79358770,"04/09 14:29 nota de Juliana")], "categoria_causa": "habilidade comercial"},
  "c5": {"nota": 2, "justificativa": "Tarefa 'Reunião ligação' para 04/09 12:00; ligação às 12:41 de 4 s (registrada na conta de integração) e uma cancelada; sem nova tentativa até 25/09 (cancelada). Sem ligação nos 21 dias de silêncio.", "evidencias": [R(79358770,"04/09 12:41 notas de chamada"), R(79358770,"25/09 14:17")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c7": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c8": {"nota": 2, "justificativa": "Chegou a Negociação em 04/09 com documentos solicitados; sem reunião registrada; em 15/09 voltou a Análise sem nota que explique.", "evidencias": [R(79358770,"04/09 14:25 etapa Negociação"), R(79358770,"15/09 15:02 volta para Análise")], "categoria_causa": "processo/distribuição"},
  "c9": {"nota": 1, "justificativa": "Follow-up de documentos previsto para 08/09 não executado; regressão de etapa sem contato; retomada só em 25/09.", "evidencias": [R(79358770,"04/09 14:26 tarefa → 25/09 14:19 conclusão")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 2, "justificativa": "Nota de caso boa; tarefas criadas; mas tarefa vencida 17 dias, regressão de etapa sem nota, ligações na conta de integração, serviço não preenchido.", "evidencias": [R(79358770,"04/09 14:29 nota"), R(79358770,"15/09 15:02")], "categoria_causa": "registro"}},
 calls_analysis=[{"call_id": "04/09 12:41 (4 s, conta de integração)", "transcript_source": "sem gravação útil", "resumo": "Ligação de 4 s (atendida e encerrada) e uma cancelada no mesmo minuto — tentativa de reunião por ligação não concretizada; a conversa seguiu por texto.", "trechos": [], "limites": "sem áudio"}],
 analysis={
  "acertos": ["Nota humana completa com os fatos do caso (referência para a equipe).", "Tarefa de reunião e tarefa de documentos criadas com prazo no dia da negociação."],
  "melhorias": ["Executar a tarefa no prazo: 'ver se encaminhou documentos' venceu em 08/09 e só foi tratada em 25/09.", "Ao regredir a etapa (15/09), registrar motivo e contatar o lead; regressão silenciosa não ajuda ninguém.", "Tentar ligação real (não 4 s) quando a reunião por ligação estava agendada; e ao menos uma ligação durante o silêncio de 21 dias."],
  "evidencias": [R(79358770,"27/08 11:19–11:24 robô e humano simultâneos"), R(79358770,"04/09 10:24 tarefa 'Reunião ligação' 12:00"), R(79358770,"04/09 14:26 → 25/09 14:15 (21 dias)")],
  "conduzir_melhor": ["Sugestão reescrita (08/09, tarefa): '[nome], conseguiu separar os documentos que combinamos (atestados, comprovantes do benefício)? Se preferir, me manda foto de um por vez.'", "Sugestão reescrita (15/09, ao regredir): 'Como ainda não recebemos os documentos, vou manter seu caso em análise. Quando conseguir, me avisa que retomamos de onde paramos.'"],
  "proxima_acao": "Não executar: ligação para retomar a coleta de documentos com dois horários; nota explicando a regressão; se sem retorno em 7 dias, motivo de perda registrado.",
  "limitacoes": ["Sem texto; a mensagem do lead de 04/09 14:26 pode não exigir resposta (regra conservadora aplicada)."],
  "confianca": "alta para tempos e tarefas; baixa para conteúdo.",
  "observado_vs_sugerido": []})

CASES["80012252"] = dict(
 ratings={
  "c1": {"nota": 1, "justificativa": "Transferência 22/09 18:54 (fora do horário comercial provável); 1ª ação humana 23/09 10:22 (15,5 h; pernoite). Após a ligação, o lead enviou ~30 mensagens (10:51–11:11) — provavelmente documentos — respondidas apenas pelo robô; nenhuma ação humana até 24/09 15:17, quando o lead foi desqualificado com 1 mensagem; as 3 respostas do lead (15:18–15:19) seguem sem retorno (103 h no corte).", "evidencias": [R(80012252,"22/09 18:54 → 23/09 10:22"), R(80012252,"23/09 10:51–11:11 mensagens do lead; robô 11:02/11:11/11:12"), R(80012252,"24/09 15:17 → 15:19 sem retorno")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": 3, "justificativa": "Abertura da ligação explica por que ligou e cita o que o lead disse ao robô ('vi que o senhor teve o período pelo INSS'); pergunta aberta em seguida.", "evidencias": [R(80012252,"23/09 10:24 transcrição 00:25–00:39")], "categoria_causa": "habilidade comercial"},
  "c3": {"nota": 3, "justificativa": "Transcrição e resumo automático da ligação de 28 min: início na empresa, afastamento, INSS, exame de retorno, mudança de cidade, transferência, laudos — situação e problema bem explorados.", "evidencias": [R(80012252,"23/09 10:53 nota (resumo automático)")], "categoria_causa": "habilidade comercial"},
  "c4": {"nota": 3, "justificativa": "A ligação qualifica de fato: identifica que o INSS já tem advogada (03:29), checa insalubridade, horas extras e FGTS (20:13–21:15) e conclui que a tese trabalhista é frágil porque a mudança de estado foi decisão do lead (24:09–24:41). O critério, porém, não foi registrado no CRM e a decisão levou 28 min para emergir.", "evidencias": [R(80012252,"23/09 10:24 transcrição 03:29–03:38, 20:13–21:15, 24:09–24:41")], "categoria_causa": "habilidade comercial"},
  "c5": {"nota": 3, "justificativa": "Ligação 2 min após a 1ª mensagem humana, 28 min de duração.", "evidencias": [R(80012252,"23/09 10:24 ligação 1669 s")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": 2, "justificativa": "Orienta o lead sobre o que fazer (justificar ausência com laudo; caminho pela empresa) e é transparente sobre a fragilidade da tese, mas não apresenta o que o escritório faria nem condições; encerra pedindo documentos sem prazo de retorno.", "evidencias": [R(80012252,"23/09 10:24 transcrição 14:52–15:14, 24:09–24:41, 27:17–27:42")], "categoria_causa": "habilidade comercial"},
  "c7": {"nota": 3, "justificativa": "Acolhe a indignação ('estou entendendo sua indignação') e devolve o fato objetivo (contrato era na Paraíba; transferência pedida depois da mudança) sem prometer.", "evidencias": [R(80012252,"23/09 10:24 transcrição 24:09–24:41")], "categoria_causa": "habilidade comercial"},
  "c8": {"nota": 2, "justificativa": "Próximo passo definido na ligação (lead envia laudos e e-mails até o fim do dia) e o lead enviou ~30 mensagens em 20 min; não houve acolhimento humano desse material.", "evidencias": [R(80012252,"23/09 10:53 nota"), R(80012252,"23/09 10:51–11:11")], "categoria_causa": "processo/distribuição"},
  "c9": {"nota": 1, "justificativa": "Documentos recebidos sem confirmação; desqualificação por 1 mensagem 29 h depois; réplicas do lead sem resposta.", "evidencias": [R(80012252,"24/09 15:17–15:19")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 1, "justificativa": "Sem motivo de perda; etapa 'Desqualificado' sem nota; tarefa automática com prazo de 5 min às 18:54 (irreal); robô respondeu 13 vezes após a transferência; tag 'humano' correta.", "evidencias": [R(80012252,"22/09 18:54 tarefa due 18:59"), R(80012252,"23/09 11:02–13:19 robô")], "categoria_causa": "integração"}},
 calls_analysis=[{"call_id": "51473ee4-a0ab-406c-9c8d-13364217a42d (23/09 10:24, 1669 s)", "transcript_source": "transcrição local (faster-whisper small) + resumo automático do CRM (notas 23/09 10:53)", "resumo": "27 min 49 s. Abertura retoma a conversa com o robô ('vi que o senhor teve o período pelo INSS'). Lead: frentista desde 05/11/2025, bursite/tendinite, INSS até fevereiro, empresa não marcou exame de retorno, 'limbo previdenciário', mudou-se para SP por conta própria, exame de retorno em SP com restrição, pediu transferência depois de já estar em SP; já tem advogada só contra o INSS. A atendente orienta (não ficar sem justificar a ausência; laudo), checa insalubridade (recebia 30%), horas extras (não), FGTS (ok), checa tempo de contribuição no INSS e, aos 24 min, confronta: 'em nenhum momento a empresa mandou você sair de lá... o contrato de trabalho era lá'. Fecha pedindo e-mails da empresa e laudo recente.", "trechos": [
    {"timestamp": "00:25–00:39", "trecho": "Eu preferi te ligar porque acredito que o senhor mandou [mensagem] fora do nosso horário. Então fui ver umas mensagens, eu vi que o senhor teve o período pelo INSS. Me explica melhor.", "interpretacao": "Boa retomada de contexto e pergunta aberta.", "alternativa": "(manter)"},
    {"timestamp": "03:29–03:38", "trecho": "[lead] E entrei com a advogada, que não tem nada a ver com a questão trabalhista. Eu entrei pedindo contra o INSS, só contra o INSS, do auxílio-acidente.", "interpretacao": "Aos 3 min o lead informa que já tem advogada para o INSS; o possível objeto do escritório seria só a parte trabalhista.", "alternativa": "Sugestão reescrita: 'Então o INSS já está com a sua advogada. Vamos focar na empresa: o que exatamente o senhor quer que a empresa faça ou pague?'"},
    {"timestamp": "14:52–15:14", "trecho": "se o senhor não tem condições de voltar para trabalhar, o senhor não pode ficar sem justificar isso para a empresa. O senhor precisa de um laudo médico ... isso é o caminho.", "interpretacao": "Orientação útil e honesta ao lead, mesmo sem contratação.", "alternativa": "(manter)"},
    {"timestamp": "24:09–24:41", "trecho": "estou entendendo sua indignação. Mas em nenhum momento a empresa mandou você sair de lá. O senhor foi para outro estado... por uma decisão do senhor... o contrato de trabalho era lá, certo? O senhor fez a solicitação da transferência só depois que já estava aqui em São Paulo.", "interpretacao": "Qualificação feita na ligação: a tese trabalhista é frágil porque a mudança foi decisão do lead. Isso explicaria a desqualificação do dia seguinte — que, porém, não foi registrada como motivo nem comunicada com fechamento.", "alternativa": "Sugestão reescrita: 'Seu Milton, vou ser transparente: como a mudança foi decisão sua, a empresa não tem obrigação de transferir. Se ela demitir ou não responder, aí muda. Vou registrar seu caso e te aviso amanhã se conseguimos ajudar em algo além do INSS.'"},
    {"timestamp": "27:17–27:42", "trecho": "Eu vou ficar aguardando o senhor me encaminhar esse e-mail, o seu laudo recente de afastamento ... para poder fazer uma análise, está bom? — Está bom, deixa eu mandar tudo aqui...", "interpretacao": "Próximo passo definido para o lead, sem prazo de retorno do escritório. Ele enviou ~30 mensagens em 20 min e não houve acolhimento humano; no dia seguinte foi desqualificado com 1 mensagem.", "alternativa": "Sugestão reescrita: 'Me manda o e-mail e o laudo. Eu analiso com o Dr. e te retorno até amanhã ao meio-dia dizendo se conseguimos assumir algo contra a empresa.'"}],
   "limites": "Transcrição automática com trechos de baixa confiança e repetições; nomes incertos."}],
 analysis={
  "acertos": ["Ligação imediata (2 min após a 1ª mensagem) e longa, com investigação ampla."],
  "melhorias": ["Acolher documentos recebidos: confirmar recebimento e prazo de retorno (30 mensagens sem resposta humana).", "Desqualificar com motivo registrado e mensagem de saída elegante (roteiro etapa 06), respondendo às réplicas do lead.", "Transferências após o expediente: combinar a regra da 1ª ação no dia útil seguinte (ex.: até 9h30) e cumpri-la.", "Confirmar o recebimento dos documentos no mesmo dia e dar prazo de retorno."],
  "evidencias": [R(80012252,"22/09 18:54 transferência"), R(80012252,"23/09 10:24 ligação 1669 s"), R(80012252,"23/09 10:51–11:11 ~30 mensagens do lead → robô"), R(80012252,"24/09 15:17 Desqualificado sem motivo")],
  "conduzir_melhor": ["Sugestão reescrita (desqualificação): 'Seu Milton, analisei o que o senhor me enviou. Pelo que temos, o caminho hoje é o pedido no INSS e não uma ação trabalhista, então não conseguimos seguir com o escritório neste momento. Se a empresa não responder à transferência ou houver demissão, me chame que reavaliamos.'"],
  "proxima_acao": "Não executar: responder às 3 mensagens de 24/09, registrar o motivo de perda e, se cabível, encaminhar orientação previdenciária.",
  "limitacoes": ["Sem texto das ~30 mensagens (podem ser documentos); sem transcrição da ligação no corte."],
  "confianca": "alta para tempos; média para conteúdo da ligação.",
  "observado_vs_sugerido": [{"ts": "2026-09-24T15:17:00-03:00", "trecho": "[1 mensagem humana + etapa 'Desqualificado' sem motivo; lead responde 3 vezes]", "interpretacao": "Encerramento sem motivo registrado e sem fechar a conversa.", "alternativa": "Sugestão reescrita acima (saída elegante com porta aberta) + motivo de perda no CRM.", "ref": R(80012252,"24/09 15:17–15:19")}]})

CASES["80064014"] = dict(
 ratings={
  "c1": {"nota": 2, "justificativa": "Lead orgânico criado e atendido por humano em 1 min; 17 mensagens humanas e respostas em minutos em 24/09. Em 25/09 08:31–08:32 o lead escreveu, o robô respondeu 3 vezes e nenhum humano respondeu até o corte (86 h, com fim de semana).", "evidencias": [R(80064014,"24/09 15:17–17:53"), R(80064014,"25/09 08:31 → sem retorno humano")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c3": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c4": {"nota": DI, "justificativa": "Sem texto; serviço não informado.", "evidencias": [], "categoria_causa": None},
  "c5": {"nota": 2, "justificativa": "Nenhuma tentativa de ligação em lead movido direto para Negociação; sem evidência de recusa.", "evidencias": [R(80064014,"24/09 15:17 etapa Negociação")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c7": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c8": {"nota": DI, "justificativa": "Etapa Negociação atribuída no 1º minuto; o que foi proposto não é verificável.", "evidencias": [], "categoria_causa": None},
  "c9": {"nota": 1, "justificativa": "Pendência aberta desde 25/09 08:32 (86 h no corte); tarefa de 15:22 não concluída.", "evidencias": [R(80064014,"25/09 08:32"), R(80064014,"24/09 15:17 tarefa vencida")], "categoria_causa": "processo/distribuição"},
  "c10": {"nota": 1, "justificativa": "Salto Novo Lead → Negociação em 1 min; tarefa vencida; sem notas; serviço vazio; robô ativo em lead humano.", "evidencias": [R(80064014,"24/09 15:17"), R(80064014,"25/09 08:31 robô ×3")], "categoria_causa": "registro"}},
 calls_analysis=[],
 analysis={
  "acertos": ["Atendimento humano imediato e intenso no 1º dia (17 mensagens, respostas em minutos)."],
  "melhorias": ["Responder à pendência de 25/09 — lead em Negociação esperando há 3,5 dias.", "Registrar o que foi negociado (nota) e criar tarefa datada; concluir a tarefa automática ou removê-la."],
  "evidencias": [R(80064014,"24/09 15:17–17:53"), R(80064014,"25/09 08:31–08:32 lead → robô ×3")],
  "conduzir_melhor": ["Sugestão reescrita (25/09 manhã): 'Bom dia! Vi sua mensagem. Posso te ligar às 11h pra fecharmos os detalhes? Leva 10 minutos.'"],
  "proxima_acao": "Não executar: responder ao lead, oferecer ligação e registrar nota da negociação.",
  "limitacoes": ["Sem texto; caso avaliado apenas por tempos e registros."],
  "confianca": "alta para tempos; baixa para condução.",
  "observado_vs_sugerido": []})

CASES["80105650"] = dict(
 ratings={
  "c1": {"nota": 3, "justificativa": "Lead de sábado (27/09 13:31) atendido pelo robô; humano entrou domingo 10:41 (19 h; fim de semana). Mensagens do lead às 11:23–11:25 tiveram só resposta do robô; humano voltou 14:20 (3 h). Depois, respostas em 5–15 min. Última mensagem do lead (14:57) seguida de desqualificação às 15:00 sem resposta identificável (texto indisponível).", "evidencias": [R(80105650,"28/09 10:41"), R(80105650,"28/09 11:23 → robô 11:23; humano 14:20"), R(80105650,"28/09 14:57 → 15:00 Desqualificado")], "categoria_causa": "processo/distribuição"},
  "c2": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c3": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c4": {"nota": DI, "justificativa": "Sem texto; robô marcou score 100 e 'horas extras não pagas'; desqualificado em 1,5 h de conversa humana sem motivo registrado.", "evidencias": [R(80105650,"27/09 13:31 campos [T]"), R(80105650,"28/09 15:00")], "categoria_causa": "registro"},
  "c5": {"nota": 2, "justificativa": "Duas ligações 'canceladas' (10:45 e 14:20) — encerradas antes de tocar/atender; não constituem tentativa efetiva; sem nova tentativa.", "evidencias": [R(80105650,"28/09 10:45 e 14:20 notas de chamada 'Cancelada'")], "categoria_causa": "habilidade comercial"},
  "c6": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c7": {"nota": DI, "justificativa": "Sem texto.", "evidencias": [], "categoria_causa": None},
  "c8": {"nota": NA, "justificativa": "Desqualificado antes de qualquer etapa de condução.", "evidencias": [], "categoria_causa": None},
  "c9": {"nota": NA, "justificativa": "Nada agendado/enviado.", "evidencias": [], "categoria_causa": None},
  "c10": {"nota": 1, "justificativa": "Sem motivo de perda; tag 'agente' mantida em lead atendido por humano; robô respondeu enquanto a humana atendia; desqualificação 3 min após a última mensagem do lead sem nota.", "evidencias": [R(80105650,"28/09 11:23–12:25 robô"), R(80105650,"28/09 15:00")], "categoria_causa": "registro"}},
 calls_analysis=[{"call_id": "28/09 10:45 e 14:20 (canceladas)", "transcript_source": "sem áudio", "resumo": "Ligações encerradas antes de completar ('Cancelada'); não houve conversa.", "trechos": [], "limites": "status 6 sem duração"}],
 analysis={
  "acertos": ["Atuação humana no domingo com respostas rápidas na tarde."],
  "melhorias": ["Registrar motivo de perda e enviar mensagem de saída ao desqualificar (roteiro etapa 06).", "Se a ligação é cancelada antes de tocar, registrar o porquê ou tentar de novo; 2 'canceladas' não são tentativas reais."],
  "evidencias": [R(80105650,"28/09 10:41–15:00")],
  "conduzir_melhor": ["Sugestão reescrita (saída): 'Obrigada por compartilhar sua situação. Pelo que temos hoje, o caminho jurídico não é o mais indicado. Se aparecer algo novo (comprovantes, mensagens, testemunhas), me chame que reavaliamos.'"],
  "proxima_acao": "Não executar: registrar motivo de perda; responder à mensagem de 14:57 com a saída elegante.",
  "limitacoes": ["Sem texto; a mensagem das 14:57 pode ser um encerramento pelo próprio lead."],
  "confianca": "média",
  "observado_vs_sugerido": []})

DIAG = {
 "acertos_gerais": [
  "Velocidade quando o lead chega em horário útil: em 6 de 8 casos com transferência identificável a 1ª ação humana veio em até 4 h (mediana ≈ 1,7 h); 3 casos em menos de 15 min.",
  "Ligação usada como canal de decisão nos casos que avançaram: 5 de 10 casos tiveram ligação atendida > 60 s; os dois ganhos com ligação/reunião longa fecharam no mesmo dia (79763954) ou com reunião registrada (79533290).",
  "Investigação ampla nas ligações longas analisadas (79877820, 77456896, 79763954): tempo de casa, função, jornada, pagamento, documentos.",
  "Registros úteis existem: notas de caso (79358770), tarefas com resultado (79533290, 79490552), ligações gravadas via API4com (10 com link, 5 acessíveis e transcritas localmente)."],
 "padroes": [
  {"comportamento": "Lead fica sem resposta humana por dias após escrever (pendência aberta no corte ou lacuna > 3 dias)", "frequencia": "4 de 10 casos com pendência aberta no corte (86 h a 103 h); 8 de 10 com ao menos uma lacuna > 3 dias entre mensagem do lead e ação humana", "evidencias": [R(80064014,"25/09 08:32 → corte (86 h, Negociação)"), R(80012252,"24/09 15:19 → corte (103 h)"), R(79490552,"24/09 17:35 → corte (101 h, pós-ativação)"), R(79358770,"04/09 14:26 → 25/09 (21 dias)"), R(79533290,"04/09 → 17/09 (13 dias)")], "impacto": "Leads em Negociação/Análise esfriam; documentos enviados não são conferidos; clientes ativados percebem abandono.", "mudanca": "Rotina diária de 'fila de leads com última mensagem do lead sem resposta humana' (incluindo pós-ativação e pós-desqualificação) com meta proposta a validar; cadência do Playbook aplicada em Negociação.", "acompanhamento": "Indicador: nº de leads com última mensagem do lead sem ação humana > 24 h (base: 4 de 10 na amostra). Responsável: gestor comercial.", "causa": "processo/distribuição"},
  {"comportamento": "Próximo passo sem prazo/horário ou sem tarefa após ligação ou reunião", "frequencia": "3 de 5 ligações/reuniões avaliáveis (79877820, 80038784, 79533290 reunião OK com tarefa; 77456896 prazos sem tarefa; 80012252 docs sem acolhimento)", "evidencias": [R(79877820,"17/09 12:33–12:52 transcrição"), R(80038784,"25/09 10:25 transcrição 02:20–02:39"), R(77456896,"25/09 11:52 resumo: 'até amanhã' e 'segunda' sem tarefa")], "impacto": "Bola fica com o lead; 1ª cobrança vem dias depois (4 dias em 79877820; nunca em 80038784).", "mudanca": "Fechar toda ligação com data/hora do próximo contato e criar tarefa no CRM antes de desligar.", "acompanhamento": "Indicador: % de ligações atendidas > 60 s seguidas de tarefa com prazo em até 1 h (base: 1 de 5).", "causa": "habilidade comercial"},
  {"comportamento": "Retomada de contexto: humano reinicia a investigação sem usar o que o robô/formulário colheu", "frequencia": "1 de 2 ligações avaliáveis com abertura audível (80038784 negativa; 79877820 positiva)", "evidencias": [R(80038784,"25/09 transcrição 00:29–02:11 'não aparece esse relatório'"), R(79877820,"17/09 transcrição 00:13–00:28")], "impacto": "Lead repete a história; percepção de desorganização.", "mudanca": "Abertura padrão de 3 linhas citando serviço, situação e o que já foi dito ao assistente; checar se o resumo do agente aparece no lead (integração).", "acompanhamento": "Amostra mensal de 5 ligações: abertura cita contexto? (base: 1 de 2).", "causa": "habilidade comercial"},
  {"comportamento": "Registro incompleto no CRM: sem motivo de perda, tarefas vencidas, etapas que não refletem a realidade, serviço vazio, ligação no usuário de integração", "frequencia": "Motivo de perda ausente: 2 de 2 desqualificados; tarefas vencidas: 3 de 10; serviço não informado: 4 de 10; etapa avançada sem contato comprovado: 2 de 10 (77456896, 80064014)", "evidencias": [R(80012252,"24/09 15:17"), R(80105650,"28/09 15:00"), R(79763954,"15/09 15:45 chamada created_by 10348307"), R(77456896,"08/06 10:49–12:07")], "impacto": "Sem motivo de perda não há aprendizado; sem tarefa não há cadência; a etapa não reflete a realidade.", "mudanca": "Motivo de perda obrigatório na etapa Desqualificado; nota curta após cada ligação; preencher 'Serviço' na triagem; concluir/limpar tarefas automáticas.", "acompanhamento": "Indicadores: % desqualificados com motivo (base 0 de 2); tarefas vencidas > 2 dias (base 3 de 10).", "causa": "registro"},
  {"comportamento": "Transferência fora do expediente gera tarefa de 5 min impossível e 1ª ação só no dia seguinte", "frequencia": "2 de 10 (80012252 às 18:54 → 15,5 h; 80038784 às 07:33 → 3,8 h)", "evidencias": [R(80012252,"22/09 18:54 tarefa due 18:59 → concluída 23/09 10:15"), R(80038784,"24/09 07:33 → 11:19")], "impacto": "Lead que acabou de falar com o robô fica sem expectativa; a tarefa vencida vira ruído.", "mudanca": "Mensagem automática de expectativa fora do expediente ('nossa equipe fala com você a partir das 9h') e prazo da tarefa calculado no horário útil. Proposta para validação, expediente não confirmado.", "acompanhamento": "Tempo transferência → 1ª ação humana em horário útil (base: mediana 1,7 h; extremos 15,5 h e 700 h por registro).", "causa": "processo/distribuição"}],
 "boas_praticas": [
  "Ligar primeiro e retornar no horário que o lead pediu, avisando antes por mensagem (79877820, 17/09).",
  "Pergunta de fechamento explícita ao fim da ligação: 'podemos dar seguimento? ficou alguma dúvida?' (79877820).",
  "Tarefa com resultado descrevendo o combinado: 'Reunião realizada. Enviar documentos para contratação…' (79533290, 24/09).",
  "Nota de caso com datas e fatos (79358770, 04/09).",
  "Persistir por ligação quando o lead não escreve (77456896: 3 atendidas em 10 tentativas)."],
 "casos_discussao": [
  {"caso": "79877820", "motivo": "Acerto (ligação em 11 min, investigação ampla) e oportunidade (fechar com prazo; implicação)."},
  {"caso": "80038784", "motivo": "Retomada de contexto falhou na ligação; encerramento sem próximo passo; sem follow-up em 3,5 dias."},
  {"caso": "80012252", "motivo": "Ligação longa seguida de 30 mensagens do lead sem retorno humano; desqualificação sem motivo."},
  {"caso": "79763954", "motivo": "Jornada completa em 5 h; discutir o pós-ativação (5 mensagens sem resposta por 13 dias)."},
  {"caso": "79533290", "motivo": "13 dias sem cadência em Negociação; reunião realizada 20 dias depois; o que mudou?"}],
 "prioridades": [
  {"titulo": "Zerar a fila de leads sem resposta humana", "descricao": "Rotina diária (manhã e tarde) sobre leads cuja última mensagem é do lead, incluindo pós-ativação e pós-desqualificação.", "frequencia": "4 de 10 pendentes no corte; 8 de 10 com lacuna > 3 dias"},
  {"titulo": "Toda ligação/reunião termina com data, hora e tarefa", "descricao": "Script de fechamento + tarefa antes de desligar; cobrança em D+1 se o combinado não chegar.", "frequencia": "3 de 5 avaliáveis sem prazo/tarefa"},
  {"titulo": "Registro mínimo: motivo de perda, serviço, nota após ligação", "descricao": "Motivo obrigatório ao desqualificar; campo Serviço na triagem; nota curta com o combinado após cada ligação.", "frequencia": "0 de 2 desqualificados com motivo; 4 de 10 sem serviço"},
  {"titulo": "Abertura com contexto do robô", "descricao": "3 linhas padrão citando serviço e situação já informados; checar exibição do resumo do agente.", "frequencia": "1 de 2 ligações avaliáveis"}],
 "plano_7d": [
  "Dia 1: listar todos os leads do funil Manual com última mensagem do lead sem ação humana; responder ou registrar motivo (gestor comercial + SDRs).",
  "Dia 2: definir quem responde às filas de pós-ativação e de documentos recebidos, e em que prazo (gestor comercial).",
  "Dia 3: adotar o script de fechamento de ligação (data + hora + tarefa) e o script de abertura com contexto; simular em dupla (SDRs).",
  "Dia 3: motivo de perda obrigatório ao desqualificar e nota curta após cada ligação (atendentes + responsável CRM).",
  "Dia 5: revisar os 10 casos do painel e executar as 'próximas ações recomendadas' que ainda fizerem sentido (SDRs).",
  "Dia 7: check-in de 20 min com os indicadores abaixo (gestor comercial)."],
 "indicadores_30d": [
  {"indicador": "Leads com última mensagem do lead sem ação humana > 24 h (contagem no funil)", "linha_base": "4 de 10 na amostra (86–103 h)", "responsavel": "Gestor comercial", "criterio": "0 pendências > 24 h em dias úteis (proposta para validação)"},
  {"indicador": "Ligações atendidas > 60 s seguidas de tarefa com prazo em ≤ 1 h", "linha_base": "1 de 5", "responsavel": "SDRs", "criterio": "≥ 4 de 5 (proposta)"},
  {"indicador": "Desqualificados com motivo de perda registrado", "linha_base": "0 de 2", "responsavel": "SDRs / responsável CRM", "criterio": "100%"},
  {"indicador": "Tempo transferência → 1ª ação humana em horário útil (mediana)", "linha_base": "≈ 1,7 h (n = 7 com transferência identificável e registro confiável)", "responsavel": "SDRs", "criterio": "manter ≤ 1 h como proposta (Playbook sugere 10 min para 1ª tentativa); expediente a confirmar"},
  {"indicador": "Ligações cuja abertura cita o contexto já informado (amostra mensal de 5 gravações)", "linha_base": "2 de 3 aberturas audíveis", "responsavel": "Gestor comercial", "criterio": "5 de 5"}
 ],
 "propostas_meta": [
  "Proposta: 1ª ação humana em até 1 h após a transferência em horário útil (Playbook FlowSales cita 10 min para 1ª tentativa; não confirmado como regra do cliente).",
  "Proposta: nenhuma mensagem do lead sem resposta humana por mais de 24 h em dias úteis, inclusive pós-ativação.",
  "Proposta: toda ligação atendida > 60 s gera tarefa com data em até 1 h.",
  "Proposta: cadência em Negociação conforme Playbook (1 h, 6 h, 24 h, 48 h, 4 d, 7 d) — hoje não observada."],
 "treinamento": {"blocos": [
  {"titulo": "1. Diagnóstico e indicadores", "tempo": "10 min", "objetivo": "Ler os indicadores com definição e cobertura; entender que 'espera aberta' é lead esperando a gente, não lead frio.", "casos": ["Visão executiva", "Comparativo ordenado por 'Espera'"], "perguntas": ["O que o lead estava esperando de nós em 80064014 (25/09) e 80012252 (24/09)?", "Quantas dessas esperas a gente sabia que existiam?"], "exercicio": "Cada SDR aponta no painel um lead seu com espera aberta e diz qual seria a próxima mensagem.", "esperado": "Reconhecer a fila de pendências como rotina diária."},
  {"titulo": "2. Casos reais: acertos e oportunidades", "tempo": "20 min", "objetivo": "Comparar 79877820 (ligação em 11 min, investigação ampla, mas sem prazo no fechamento) com 80038784 (contexto perdido, ligação sem próximo passo) e 79763954 (jornada de 5 h).", "casos": ["79877820 — transcrição 00:13–00:28 e 12:33–12:52", "80038784 — transcrição 00:29–02:39", "79763954 — linha do tempo 15/09", "80012252 — 23/09 10:51–11:11"], "perguntas": ["Na ligação da Cybele com a Liana, em que momento faltou a implicação?", "O que a atendente já sabia sobre o Bruno/‘senhor’ antes de ligar? Onde isso estava no CRM?", "Depois dos 30 envios do Milton, qual mensagem de 1 linha mudaria a percepção dele?"], "exercicio": "Ler em voz alta o fechamento 12:33–12:52 e reescrever com prazo e horário.", "esperado": "Identificar o ponto exato de retomada e de fechamento datado."},
  {"titulo": "3. Simulações", "tempo": "15 min", "objetivo": "Praticar abertura com contexto, convite à ligação, fechamento com data/hora e acolhimento de documentos.", "casos": ["Gatilhos: 80038784 (abertura), 79533290 (D+1 sem resposta), 77456896 (pós-ligação com compromissos), 80012252 (documentos recebidos)"], "perguntas": ["Como você abriria a ligação sabendo score 94, carteira assinada, horas extras?", "Como pede um horário quando o lead diz 'depois eu entro em contato'?"], "exercicio": "Duplas SDR × lead, 3 min por rodada, feedback pela rubrica (critérios 2, 5, 8, 9).", "esperado": "Abertura em 3 linhas com contexto; ≤ 2 perguntas por envio; próximo passo com data/hora e tarefa.", "exemplos": ["Sugestão reescrita — abertura: 'Vi que você falou com nosso assistente sobre horas extras não pagas, com carteira assinada há mais de 3 anos. Está podendo falar 10 minutos agora?'", "Sugestão reescrita — fechamento: 'Vou te mandar a lista agora. Consegue enviar até as 18h? Amanhã às 10h eu te chamo aqui pra conferir.'", "Sugestão reescrita — documentos recebidos: 'Recebi tudo, obrigado. Vou analisar e te retorno até amanhã 12h.'", "Sugestão reescrita — saída elegante: 'Pelo que temos hoje, o caminho jurídico não é o mais indicado. Se aparecer algo novo, me chame que reavaliamos.'"]},
  {"titulo": "4. Checklist e compromissos operacionais", "tempo": "10 min", "objetivo": "Fechar um checklist mínimo por atendimento e os ajustes de integração/registro.", "casos": ["Diagnóstico → padrões de continuidade e de registro"], "perguntas": ["Quem responde ao cliente depois da ativação?", "Quem confirma o recebimento de documentos e em quanto tempo?"], "exercicio": "Escrever juntos o checklist: (1) abrir com contexto; (2) ligar no 1º contato em horário útil; (3) próximo passo com data/hora + tarefa; (4) confirmar recebimento de documentos; (5) motivo de perda + mensagem de saída; (6) nota curta após ligação.", "esperado": "Acordo sobre o checklist e sobre quem responde a cada fila."},
  {"titulo": "5. Plano de ação e revisão", "tempo": "5 min", "objetivo": "Confirmar prioridades, ações de 7 dias e indicadores de 30 dias com responsáveis por função.", "casos": ["Diagnóstico → plano de melhoria"], "perguntas": ["Qual indicador cada um acompanha?"], "exercicio": "—", "esperado": "Linha de base e critério de evolução aceitos como proposta para validação."}]}
}

NOMES = {"79877820": ["Liana", "Eliana", "Oriana", "Cibene", "Cinelli", "Anne"], "80012252": ["Milton"], "77456896": ["Rômulo", "Romulo", "Sibeli"], "79763954": ["Wellington", "Rabilli", "Joab", "Elisson"],
         "80038784": ["Bruna", "Bruno", "Sibeli", "Sibela", "Brin"], "79358770": [], "79490552": [], "79533290": [], "80064014": [], "80105650": []}
GERAIS = ["Cybele", "Cibele", "Juliana", "Sibela", "Sibeli", "Cibene"]

EXTRA_EVENTS = {
 "79877820": [{"id": "m-prop-79877820", "lead_id": "79877820", "ts": "2026-09-17T15:03:00-03:00", "channel": "call", "direction": "out", "actor_type": "human", "actor_name": "Cybele Gomes", "action": "proposal_presented", "content": "condições apresentadas na ligação: ação trabalhista, honorários 30% no êxito, processo online (transcrição 07:34–08:03)", "ts_precision": "min", "source": "kommo_api", "ref": R(79877820, "17/09 14:55 ligação 775 s · transcrição local 07:34–08:03"), "meta": {"confirmed": True}}],
 "77456896": [{"id": "m-prop-77456896", "lead_id": "77456896", "ts": "2026-09-25T11:45:00-03:00", "channel": "call", "direction": "out", "actor_type": "human", "actor_name": "Cybele Gomes", "action": "proposal_presented", "content": "condições apresentadas na ligação: 30% dos atrasados + 30% dos 12 primeiros meses; prazo 3–4 meses (resumo automático)", "ts_precision": "min", "source": "kommo_api", "ref": R(77456896, "25/09 11:52 nota 'Resumo Gerencial'"), "meta": {"confirmed": False, "fonte": "resumo automático"}}],
 "79763954": [{"id": "m-prop-79763954", "lead_id": "79763954", "ts": "2026-09-15T16:10:00-03:00", "channel": "call", "direction": "out", "actor_type": "undetermined", "actor_name": "Marketing Evolve (conta de integração/compartilhada)", "action": "proposal_presented", "content": "processo e prazo de elaboração (10 dias úteis) apresentados na ligação (resumo automático)", "ts_precision": "min", "source": "kommo_api", "ref": R(79763954, "15/09 16:14 nota 'Resumo Gerencial'"), "meta": {"confirmed": False, "fonte": "resumo automático"}}],
}

def main():
    for lid, data in CASES.items():
        data["analysis"]["nomes_citados"] = NOMES.get(lid, []) + GERAIS
        p = f"{LEADS}/{lid}.json"
        c = json.load(open(p))
        c["ratings"] = data["ratings"]; c["calls_analysis"] = data["calls_analysis"]; c["analysis"] = data["analysis"]
        c["events"] = [e for e in c["events"] if not str(e["id"]).startswith("m-prop-")] + EXTRA_EVENTS.get(lid, [])
        c["events"].sort(key=lambda e: e["ts"])
        json.dump(c, open(p, "w"), ensure_ascii=False, indent=1)
    json.dump(DIAG, open(os.path.join(ROOT, "dados/restrito/analise.json"), "w"), ensure_ascii=False, indent=1)
    print("análise gravada em", len(CASES), "casos + analise.json")

if __name__ == "__main__":
    main()
